# Generated by Django 4.0.5 on 2022-06-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='имя')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('date_in', models.DateField()),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('supplier_name', models.CharField(max_length=128)),
                ('category', models.ManyToManyField(default='', to='productapp.productcategory')),
            ],
        ),
    ]
