# Generated by Django 4.0.5 on 2022-06-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('date_in', models.DateField()),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('supplier_name', models.CharField(max_length=128)),
            ],
        ),
    ]
