# Generated by Django 4.0.5 on 2022-06-17 11:55

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('productapp', '0003_alter_product_managers_product_site'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productcategory',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='site',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
